# Generated by Django 6.0.7 on 2026-07-16 18:28

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CompanyProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='Distribuidora Pollo Rey', max_length=180)),
                ('rtn', models.CharField(blank=True, max_length=30)),
                ('address', models.CharField(default='Olanchito, Yoro, Honduras', max_length=240)),
                ('phone', models.CharField(blank=True, max_length=40)),
                ('email', models.EmailField(blank=True, max_length=254)),
                ('default_tax_rate', models.DecimalField(decimal_places=2, default=15, max_digits=5)),
                ('currency', models.CharField(default='HNL', max_length=10)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
